theme: jekyll-theme-slate
title: Sytske Wijnsma
description: PhD Candidate University of Cambridge
avatar: https://user-images.githubusercontent.com/83771707/126292097-c8f9af7a-3fab-4c83-b345-90449d4dbbae.jpg
